module.exports = {
  apps: [
    {
      name: 'barsha-backend',
      script: './server.js',
      cwd: '/opt/barsha-backend',
      // Use a single forked instance. The backend starts a background calling
      // queue (startCallingQueue), so running multiple instances would risk
      // duplicate outbound calls.
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 5001,
        LEAD_IMPORT_WORKER_ENABLED: 'false',
      },
      // Logs are written relative to cwd unless absolute paths are provided.
      error_file: '/var/log/barsha-backend/err.log',
      out_file: '/var/log/barsha-backend/out.log',
      log_file: '/var/log/barsha-backend/combined.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 5000,
    },
    {
      name: 'barsha-lead-import-worker',
      script: './workers/lead-import.worker.js',
      cwd: '/opt/barsha-backend',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        LEAD_IMPORT_WORKER_CONCURRENCY: 2,
      },
      error_file: '/var/log/barsha-backend/lead-import-worker-err.log',
      out_file: '/var/log/barsha-backend/lead-import-worker-out.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 10000,
    },
    {
      name: 'barsha-send-email-worker',
      script: './workers/send-email.worker.js',
      cwd: '/opt/barsha-backend',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production' },
      error_file: '/var/log/barsha-backend/send-email-worker-err.log',
      out_file: '/var/log/barsha-backend/send-email-worker-out.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 10000,
    },
    {
      name: 'barsha-poll-inbox-worker',
      script: './workers/poll-inbox.worker.js',
      cwd: '/opt/barsha-backend',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production' },
      error_file: '/var/log/barsha-backend/poll-inbox-worker-err.log',
      out_file: '/var/log/barsha-backend/poll-inbox-worker-out.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 10000,
    },
  ],
};
